---
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  global:
    - SCOUT_DISABLE=1
    - secure: "elVwcLP2n04gNRBRfMl0+s0qiFOzZ9mqDBpyV5ylpkRdAdNQStAwLEyGs9cQsXTDwRuAPPffMPcBapwwJVoKIETcUE6RsFsK90y54w7yZKwtRLZvLv9K/XSaPsDdLiOZSDkejA5SB9M+FgseVCmV4pURRXqUxgtNoHDMbIZYF/9xKzjslTlBlwgsPprs5Nv5Pp6gxL3h+n9j3fM3gNIenSsz1un1DG0ly+kWU2KMu0ujj1yLAUVpXn3BYM+h1nuCmqUhm4/z5Bwqv3NuWyDkOmIJs72KhRZpdwDb0tn041pAXAdjCFM0vdQXbskwoN9sN5Ql4g+OamdereIUW4ZP3s5GmQ8YfJYWVizn9jmfXY2KZWjmuRebtpktAjbfpmIeriVli+IAXiIshiM++/4uSyvDHOQ8otVy38HmWD+6T0ci7ZPggHqYGLt7QGxZgKhi0f/JoVYzpWRLxpuspIT7yLJyRXvSDvlUUsOe0VfTSNH3lLzF+gTpfsskgmVnDJZ2ma/qhibwwBxOTJAh7dXt30vBqqv4shRKVzCTUSuYnUANWU24K4Rc5Tj2hQlKjaTJRri1v8LD+rkg1EhF9hj290EI7SDjuXTpmOjccyr+bSkgqHZXZynnlMcOVzixXzj7Ep3PpPEDgo4i2hk9nN8LGvNCxUOFafE+VyXWlaGov6k="

services:
  - docker

# Only build master branch and tags of form 0.1 or 1.0.2 (all PRs will be built):
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?$/

before_install:
  - gem install package_cloud
  - package_cloud version
  - which package_cloud

  - pip install tox-travis homebrew-pypi-poet awscli
  - python --version
  - python2 --version
  - python3 --version

install:
  - make virtualenv

script:
  - export KUBERNAUT_VERSION=$(make version)
  - tox
  - virtualenv/bin/pip install .
  - rm -f ~/.config/kubernaut/config.json
  - virtualenv/bin/kubernaut --version
  - echo "{}" > ~/.config/kubernaut/config.json
  - virtualenv/bin/kubernaut --version

deploy:
  provider: script
  skip_cleanup: true
  script: ci/release.sh
  on:
    tags: true
    branch: master
